# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jpawitro's Space
name: Joko Pawitro
occupation: '| Asset Engineer | Data Scientist | Business Analyst |'
email: jpawitro@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Joko Pawitro's personal page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

occupations:
  - company : Ørsted
    description: Ørsted A/S (formerly DONG Energy) is a Danish multinational power company based in Fredericia, Denmark. It is the largest energy company in Denmark and the world's largest developer of offshore wind power by number of built offshore wind farms.
    url: https://orsted.com
    social:
      linkedin: orsted
      twitter: Orsted
      instagram: orsted
      youtube: '@Orsted'
    logo: assets/images/Orsted.png
    image: assets/images/orsted_banner.png
    role: Cable Monitoring Specialist 
    responsibility: A data scientist role responsible for organizing data, developing analyses, and programming solutions to ensure the availability of 30-400 kV offshore and onshore cable connections.
  - company: Practicum
    description: Practicum is an international training bootcamp that are 100% online and part time which offer various software engineering and data analytics courses. The company help people with versatile backgrounds learn a new profession online and kick start a sustainable career in tech
    url: https://practicum.com
    social:
      linkedin: practicum-indonesia
      twitter: PracticumUSA
      instagram: practicum.indonesia
      youtube: '@practicumindonesia8423'
    logo: assets/images/Practicum.png
    image: assets/images/practicum_banner.png
    role: Data Scientist / Data Analyst Mentor
    responsibility: Assist the students to understand the concepts of data analysis and data science. Conducting webinar on industrial application and professional development coaching.

social:
  twitter: jpawitro
  github:  jpawitro
  linkedin: jpawitro
  instagram:  jpawitro
  youtube:
  medium:

# Build settings
# theme: jekyll-theme-hydejack
# remote_theme: hydecorp/hydejack@v9
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
